spring.application.name=keeper-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/your_database_name
spring.datasource.username=postgres_username
spring.datasource.password=postgres_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

<<<<<<< HEAD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
=======
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
>>>>>>> d0475db187d9c86aabc63cd47ed66d5d26e2cfc2
